### ISSUE TITLE
Detach repo from upstream

### ISSUE THREAD

**Issue by aleneum** [caretech-owl/Llama-2-Open-Source-LLM-CPU-Inference#9]
I guess we have no intention to be compatible to the upstream repo or create a PR. I could trigger a detach from upstream via a GitHub bot. @Ashtonville, @Depo14: What do you think? Another benefit would be that our `main` branch will become the default PR target.

**Comment by Ashtonville** [comment]
Ja, kann gemacht werden.

**Comment by aleneum** [comment]
Filed a ticket:

https://support.github.com/ticket/2424293

**Comment by aleneum** [comment]
Done
